error.call.external.endpoint=Erro ao chamar o endpont externo